# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8e82d0b9235aca8f5cd821c897dac86e0394aed1188595298c0bdf7a0b65f76eaa45f609ed33386dd04363f0c619e28163b0c24c0c3d1dff87e6fb1f1da06bf5

test:
  secret_key_base: 88d1be5b5ba9505c1a7a1936faa2097e64529454c8b78e9faec8588c53903f3b8d8c9898fb676139ab3e4c7614df54d25d85bf6cc5c0e3d062a1cd7bedec8349

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
